name: flutter_firebase
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.3
  firebase_auth: ^0.14.0+5
  firebase_storage:
  uuid:
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

